name: Selenium MongoDB Test

on:
 push:
  branches: [ main ]

jobs:

 test:

  runs-on: ubuntu-latest

  services:

   mongo:

    image: mongo

    ports:
     - 27017:27017

  steps:

  - uses: actions/checkout@v4

  - uses: actions/setup-node@v4

    with:
     node-version: 18

  - run: npm install

  - run: node server.js &

  - run: npx wait-on http://localhost:3000

  - run: npm test